version: "3"
services:
  postgres:
    image: "postgres:latest"
  facerecognition:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3003"
    volumes:
      - /app/node_modules
      - ./:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/api/node_modules
      - ./api:/app/api
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
